### ISSUE TITLE
En passant problem

### ISSUE THREAD

**Issue by boulayo** [onspli/chess#9] opened 2022-06-07 21:23 UTC
When I move a pawn by two squares it always register the "en passant" target square in the FEN, even if it's not possible to capture en-passant.
This is a problem because it's expected that the same position is described by exactly one FEN code, and it's not the case.

For example these lines end up in the same position, with the same possibilities, but they led to two different fens:
- Nf3 Nc6 h3 d5
- Nf3 d5 h3 Nc6

**Comment by onspli** [comment] 2022-06-07 21:38
Hi, according to FEN specification, en passant square is recorded regardless of whether there is a pawn in position to capture en passant.
Closing this issue as this is not a bug but expected behaviour.

**Closed as completed by onspli** 2022-06-07 21:38 UTC
Labels: wontfix
